module CsvSimpleExport
  class Action
    # Parameters
    type header = String
    type input = Symbol | Proc

    attr_reader key: header

    attr_reader action: untyped

    attr_reader block: untyped

    def initialize: (header key, ?untyped? action) { () -> String } -> void

    def get_value: (Object record, Object host) -> String
  end
end
